package org.imperiocobra.companion.probabilities.chest

val ChestRewards = listOf(
    "Vara",
    "Martillo",
    "Espada",
    "Daga",
    "Lanza",
    "Guadaña",
    "1.00 de oro",
    "Botas",
    "Armadura",
    "Amuleto",
    "Guantes",
    "Brújula",
    "Manoplas bañadas en bronce",
    "Flautín perdido de David Jones",
    "Daga de Midas",
    "Monedero",
    "Mochila",
    "Caldero",
    "Navaja suiza",
    "Moneda Tamprosa",
    "Poción de curación",
    "Poción de defensa",
    "Poción de vigor",
    "Poción de fuerza",
    "Poción de velocidad",
    "Poción de pies ligeros",
    "Poción de invisibilidad",
    "Poción de suerte",
    "Pergamino de mejora",
    "Pergamino del explorador",
    "Pergamino de retorno",
    "Chaleco lleno de dinamita",
    "Runa sulfúrica",
    "Pala",
    "Mapa",
    "Escudo",
    "Recompensa Legendaria",
)